apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sayurpintar-api-ingress
  namespace: sayurpintar
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.sayurpintar.com
      secretName: sayurpintar-api-tls
  rules:
    - host: api.sayurpintar.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sayurpintar-api-service
                port:
                  number: 80
